### ISSUE TITLE
Turn overlays OFF?

### ISSUE THREAD

**Issue by jpaulickcz** [iPwnWolf/Nextcloud-Shell-Overlays#1]
Hi, I was wondering whether the script could be edited to actually turn the overlays off?

**Comment by Sim0nW0lf** [comment]
I can do that easily. Why would you like to turn them off?
Cheers :)

jpaulickcz <notifications@github.com> schrieb am Mi., 4. Nov. 2020, 21:32:

**Comment by Sim0nW0lf** [comment]
> Hi, I was wondering whether the script could be edited to actually turn the overlays off?

I have added an option to delete the NC overlay icons now.
ff9d59285f20c854c5e8a97fa32d53cb149be55d

**Comment by jpaulickcz** [comment]
Awesome, thank you! 💯  I'll go play with it.

The reason is quite simple actually - I want as little signs of Nextcloud client running as possible (apart from the black and white icon in the tray) – all for the clean look and not confusing users (where not necessary 😃  ). 

I've found out that if I install the client without the context menus then there are no overlay icons from the start, but I did install it on the first 3 or 4 machines and didn't figured out a way to remove them (though I only tried uninstalling the client and then installing it again without context menu options, to no avail).

**Comment by Sim0nW0lf** [comment]
That makes sense :)
Hope it works out for you 👍

**Comment by jpaulickcz** [comment]
Way overdue, but thanks! It works great!

Other thing that they told me is that in List view where the icons are really small the users couldn't tell what kind of document that file is, because the Nextcloud overlay covers the Word/Excel/etc. logo and that it was driving them mad, so that's another reason it might be useful to some. (The overlays came back on after Nextcloud update I suppose.)
